#!/usr/local/bin/python3


import arg_proc
import pq_args
import click
import Packet_Tweet


__author__ = 'SomeClown'

"""
Command Line Twitter Client
The goal of this project is to implement all functionality from the Twitter API via a traditional Unix interface.
"""

EPILOG = '... add search methods here. Need to overload class where Epilog is defined, to allow LF'


@click.group(chain=True, epilog=EPILOG)
def cli():
    """
    Command line Twitter (and stuff) client - For questions contact @SomeClown
    """


@click.command(help='Get \'n\' number of recent tweets from main feed <num>')
@click.argument('number', default=10)
@click.option('-u', '--user', 'user', help='twitter user to run command as, if not the current logged in user')
def start_friend_list(user, number):
    try:
        Packet_Tweet.init_curses()
        run_friends = Packet_Tweet.TweetArguments()
        run_friends.print_friends(number)
    except SystemExit:
        raise
    except KeyboardInterrupt:
        raise
    except BaseException as e:
        print(e)


cli.add_command(start_friend_list, 'friends')


def main() -> object:
    #my_command_args = pq_args.argumentsParsing()
    #arg_proc.arglebarg(my_command_args)
    return None

cli()
