user                    : 
home                    : 
access_token            : 
access_token_secret     : 
consumer_token          : 
consumer_token_secret   : 
friend_file             : .friends
followers               : .followers
no_follow               : .no_follow
post_limit              : 1.5
